### ISSUE TITLE
Reduce verbosity in log

### ISSUE THREAD

**Issue by xtvdata** [NorthernMan54/homebridge-dht#15]
Hi, thanks for the great plugin.

Would be useful to introduce a parameter to reduce verbosity of logging in syslog.

E.g. conditionally execute:
`this.log("DHT Status: %s, Temperature: %s, Humidity: %s", result[0], temperature, humidity);` at line 97
and
`this.log("Got Temperature of %s", binaryState);` at line 136.
(ref. code at tag v0.1.20)

**Comment by NorthernMan54** [comment]
That's a great idea, how about creating a pull request with the changes you are thinking about and I will publish it.  For the feature, if you could default it to log, much appreciated.
