### ISSUE TITLE
Support for dht11

### ISSUE THREAD

**Issue by sincetomorrow** [NorthernMan54/homebridge-dht#17]
Hello and nice work!! 
One question, does it support dht11? I have tried to replay at the service dht11 instead of dht22 but had no luck.

Thank you

**Comment by NorthernMan54** [comment]
Panos,

It should but I have don’t have one to test, so it may be a little bit of trial and error.

The core of the plugin is the dht22 binary, that gets run every time the plugin wants temperature.  If you run the dht22 command does it return temp and humidity on the command line?

If yes, the don’t change anything from the plugin config.

**Comment by Namelessinterester** [comment]
It works fine with my DHT11, but "service":   "dht22", so I just removed it from my config.

**Comment by LeoCal** [comment]
Great job @NorthernMan54 !

**Comment by NorDroN** [comment]
@Namelessinterester, could you give a part of your config for dht11?

**Comment by NorthernMan54** [comment]
The config for DHT11 and DHT22 is the same, just follow the directions for the dht22, and don’t change anything.  It should just work.

**Comment by NorDroN** [comment]
@NorthernMan54 unfortunately it does't work, I see 0°C and 0% :(

**Comment by NorthernMan54** [comment]
And if you run the dht22 command from the command line do you see the same?
