### ISSUE TITLE
dhtExec function failed: Error: spawn dht22 ENOENT

### ISSUE THREAD

**Issue by daniel4099** [NorthernMan54/homebridge-dht#19]
Doesn't work the error:

dhtExec function failed: Error: spawn dht22 ENOENT

anyone can help ?

**Comment by NorthernMan54** [comment]
ENOENT means Error no entity or file not found

Did you follow step 7.2 here?

https://www.instructables.com/id/RPIHomeBridge-TemperatureHumidity-Sensor/
