### ISSUE TITLE
Data History 

### ISSUE THREAD

**Issue by backfisch88** [NorthernMan54/homebridge-dht#25]
Hi 

Since the last Update the history always Show 0 degree (the hum 0%) in history (EVEapp)
Is there Any way to get it to work?

**Comment by backfisch88** [comment]
https://s16.directupload.net/images/190417/cxtbzktq.png

Here is a pic of the Bug

**Comment by NorthernMan54** [comment]
Let me look into this.

**Comment by NorthernMan54** [comment]
Fixed in version, 0.1.24, please update and try again

**Comment by backfisch88** [comment]
Seems to work. Thank you for this fix! Love this Plugin!

**Comment by NorthernMan54** [comment]
Good luck
