### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by toshibochan** [NorthernMan54/homebridge-dht#35]
Thank you for the plugin.
I have request.
Because iOS 13 is combining se sensor together can you make humidity and temperature as separate devices?

**Comment by NorthernMan54** [comment]
Reading this 

It is fixed in the 13.2 beta.

https://homekithero.com/2019/10/02/whats-new-in-the-home-app-in-ios-ipados-13-2-developer-beta-1

**Comment by toshibochan** [comment]
I glad Apple will add this option. Thanks.
