### ISSUE TITLE
Installation error on RPi3 with Buster

### ISSUE THREAD

**Issue by chimcen** [NorthernMan54/homebridge-dht#37]
Hi,

thank you for your plugin - but i got an error during installation.
I‘ve followed your instruction, installed bcm lib before, but i got an erren when installing your plugin on my Pi with Raspian Buster.

Here are the errors:
.......................................................................................................................................................................................
make: *** [node_dht_sensor.target.mk:110: Release/obj.target/node_dht_sensor/node-dht-sensor.o] Fehler 1
make: Verzeichnis „/usr/local/lib/node_modules/homebridge-dht-rpi/node_modules/node-dht-sensor/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.75-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-dht-rpi/node_modules/node-dht-sensor
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-dht-sensor@0.0.34 postinstall: `node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-dht-sensor@0.0.34 postinstall script.
.......................................................................................................................................................................................

And here is the complete terminal output:
[Homebridge-DHT-Install-Error.txt](https://github.com/NorthernMan54/homebridge-dht/files/3827171/Homebridge-DHT-Install-Error.txt)

**Comment by NorthernMan54** [comment]
The issue is with the installation of this module, https://github.com/momenso/node-dht-sensor and I think I have it grabbing an older version.

Let me look into it.

**Comment by NorthernMan54** [comment]
I updated the dependant libraries to the latest version, please re-install the plugin and try again.

**Comment by chimcen** [comment]
Awesome - it works like a charm.

Some questions:
1) is it possible to combine temp and hunidity to one"sensor" - just to display the dht22 the same way as the BME280 from your mcuiot project in Apple Home or Eve App?

2) The refresh time is in minutes or seconds entered in config.json?

3) Is it possible to add an +/- offset to the meassurements of the dht22? eventually directly in config.json?

Thank you :)

**Comment by NorthernMan54** [comment]
Some questions:

1. is it possible to combine temp and humidity to one"sensor" - just to display the dht22 the same way as the BME280 from your mcuiot project in Apple Home or Eve App?

_Are you referring to the iOS 13 behaviour?_  
![IMG_3889](https://user-images.githubusercontent.com/19808920/68816328-18b4ba80-064c-11ea-8183-93e42448a14d.PNG)

_Basement is a DHT22, and Cold Cellar is a MCUIOT_

2. The refresh time is in minutes or seconds entered in config.json?
 
_It is in seconds, I fixed the README me to include this_


3. Is it possible to add an +/- offset to the meassurements of the dht22? eventually directly in config.json?

_That is not a current feature, if you are looking for accuracy you may want to use the BME280 instead.  The DHT22 are horribly inaccurate.  But if you really want it, I would gladly accept a pull request with this a new optional feature._

**Comment by NorthernMan54** [comment]
After looking at the iOS 13 behaviour, I made it match the MCUIOT behaviour, update to the latest and try again

**Comment by chimcen** [comment]
It works - thank you :)

To point 3) - ...I’ve actually no idea how to do this...
