### ISSUE TITLE
Not showing humidity and temperature as two sensors on home screen (DHT22) 

### ISSUE THREAD

**Issue by knopfy** [NorthernMan54/homebridge-dht#38]
Yesterday I set up a new raspberry 3, installed homebridge and the homebridge-dht plugin. Everything works well so far. But on the home screen only temperature shows up. I can see humidity if I click on edit and then on the sensor icon. How can I get both temperature AND humidity readable from the home screen icon?

**Comment by toshibochan** [comment]
In the home app you can separate in the accessory setting.

**Comment by acoolax** [comment]
> In the home app you can separate in the accessory setting.

How? I didn't find it :-(

**Comment by NorthernMan54** [comment]
With the changes in accessory grouping behaviour with iOS 13, I had to make some changes.  And what your seeing is the current behaviour

The new behaviour

![IMG_4151](https://user-images.githubusercontent.com/19808920/69387902-4970a180-0c95-11ea-938c-74878a14079e.PNG)

The Icon on the right is what happened with iOS 13, and the left icons are the current behaviour.

![IMG_4152](https://user-images.githubusercontent.com/19808920/69387985-83da3e80-0c95-11ea-9355-120b93c74e5c.PNG)

**Comment by Penpal1278** [comment]
Hi, based on the previous comments, I understand that there were some changes made to accommodate changes in iOS 13, but is there still a way to separately display temperature and humidity in the Home app as two different sensors?  (Currently using this plugin with a DHT11; I only see a single sensor in my Home app, which displays current temp on its icon)

**Comment by NorthernMan54** [comment]
Nope unless Apple changes there grouping
