### ISSUE TITLE
Cant get it to work with DHT11

### ISSUE THREAD

**Issue by HeroCity99** [NorthernMan54/homebridge-dht#39]
Doesn't seem to be working with DHT11. 
The output remains (stuck) at 0. 
Any help would be much appreciated

**Comment by NorthernMan54** [comment]
Can you validate the wiring, by trying the sample here

https://github.com/momenso/node-dht-sensor#first-example

This is the library I’m using to connect to the device

I suspect I may have a code problem, as I don’t have a dht11 to test with

**Comment by HeroCity99** [comment]
The wiring is correct, tried different variations but nothing is working. I noticed "Service" must be "dht22" or I can just not include the line, otherwise "dht11" for "service" won't run. 
I think dht11 is not part of your code maybe?

**Comment by NorthernMan54** [comment]
Update and try again.  I added a line for the dht11

**Comment by NorthernMan54** [comment]
Service should be dht11 for the Dht11

**Comment by HeroCity99** [comment]
You are the MAN!
"gpio" should be specified and now its working! 
Thanks buddy!

**Comment by NorthernMan54** [comment]
Glad to hear
