### ISSUE TITLE
How to separate humidity from temperature

### ISSUE THREAD

**Issue by neo3** [NorthernMan54/homebridge-dht#40]
Since the penultimate update, humidity is showing up along with the temperature and I can't separate it.

My iPhone is on iOS 13.2.3 and does not have the option to separate, my homebridge config is:

        {
            "accessory": "Dht",
            "name": "Sensor",
            "name_temperature": "Temperatura",
            "name_humidity": "Umidade",
            "gpio": "23",
            "service": "dht22"
        }

Homebridge Dht
homebridge-dht v0.1.32

**Comment by NorthernMan54** [comment]
With the changes around iOS 13, this is no longer available

**Comment by neo3** [comment]
Is there any way to show separate at Homebridge?

**Comment by NorthernMan54** [comment]
Nope
