### ISSUE TITLE
Only one sensor

### ISSUE THREAD

**Issue by acoolax** [NorthernMan54/homebridge-dht#41]
Since version 1.31 its shown as one sensor of temp with info about humidity inside. In version 1.30 its shown as two different sensor. Maybe you correct this. (iOS 13.2.3)

**Comment by NorthernMan54** [comment]
With version 1.3.1, I changed the behaviour as with iOS 13 it was no longer showing the temperature on the main screen. Current version shows the temperature

**Comment by acoolax** [comment]
I have iOS13 with version 1.30. Everything showing fine.
![IMG_0082](https://user-images.githubusercontent.com/23322760/70262041-45b44300-179c-11ea-9fe7-be60ee2888fb.PNG)
but with 1.31 is not

**Comment by NorthernMan54** [comment]
Pls update and try again
