### ISSUE TITLE
Cant get Automation based on Sensor reading to work

### ISSUE THREAD

**Issue by osterland** [NorthernMan54/homebridge-dht#42]
Does anyone has deeper insights on this? Maybe there is just sth. in the config missing to get it to work? 

[https://github.com/nfarina/homebridge/issues/1444]

best, 

Kevin

**Comment by NorthernMan54** [comment]
I’m sorry this is not part of the plugin, and I’m not sure how to resolve

**Comment by osterland** [comment]
actually i could get it to work, if i create my automations with an app called „hesperus“

once created im able to edit these automations in the regular home app

thats amazing for me, but i dont have any cloue why its working

maybe this helps the one or other

Von meinem iPhone gesendet

Am 16.12.2019 um 23:05 schrieb Northern Man <notifications@github.com>:

﻿I’m sorry this is not part of the plugin, and I’m not sure how to resolve

**Comment by NorthernMan54** [comment]
For my automations, I use node-red and the Homebridge-automation node
