### ISSUE TITLE
DHT22 does not work, show as 0C and 0%.

### ISSUE THREAD

**Issue by nuttdam** [NorthernMan54/homebridge-dht#44]
I have install BCM2835 (downloaded at /home/pi) and homebridge-dht both from config-ui-x and using command line with `--unsafe-perm` and this is my config.json
`{
            "accessory": "Dht",
            "name": "Room",
            "service": "dht22"
        }`
but everything shows as 0 celcius and 0% humidity.

I am connecting DHT22 at GPIO4 (pin7) and I think I have follow through every steps, any suggestion?

Thanks

**Comment by NorthernMan54** [comment]
Do the homebridge logs show any errors?

**Comment by nuttdam** [comment]
> Do the homebridge logs show any errors?
> […](#)
> On May 27, 2020, at 2:52 PM, nuttdam ***@***.***> wrote: ﻿ I have install BCM2835 (downloaded at /home/pi) and homebridge-dht both from config-ui-x and using command line with --unsafe-perm and this is my config.json { "accessory": "Dht", "name": "Room", "service": "dht22" } but everything shows as 0 celcius and 0% humidity. I am connecting DHT22 at GPIO4 (pin7) and I think I have follow through every steps, any suggestion? Thanks — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

> [5/28/2020, 10:52:54 AM] [Room] Initializing Dht accessory...
> [5/28/2020, 10:52:54 AM] [Room] Adding Accessory
> [5/28/2020, 10:52:54 AM] [Room] INIT: Room

This is the only log I got.
By the way I try to manage this to work by adding refresh interval setting to json with value of 1.

> {
>             "accessory": "Dht",
>             "name": "Room",
>             "gpio": "4",
>             "service": "dht22",
>             "refresh": "1"
>         }

Now the log shows

> [5/28/2020, 10:55:58 AM] [Room] DHT Status: 0, Temperature: 28.9°C, Humidity: 77.9%
> [5/28/2020, 10:55:58 AM] [Room] DHT Status: 0, Temperature: 28.9°C, Humidity: 77.9%
> [5/28/2020, 10:55:58 AM] [Room] DHT Status: 0, Temperature: 28.9°C, Humidity: 77.9%
> [5/28/2020, 10:55:58 AM] [Room] DHT Status: 0, Temperature: 28.9°C, Humidity: 77.9%
> [5/28/2020, 10:55:58 AM] [Room] DHT Status: 0, Temperature: 28.9°C, Humidity: 77.9%
> [5/28/2020, 10:55:58 AM] [Room] DHT Status: 0, Temperature: 28.9°C, Humidity: 77.9%
> [5/28/2020, 10:55:58 AM] [Room] DHT Status: 0, Temperature: 28.9°C, Humidity: 77.9%
> [5/28/2020, 10:55:58 AM] [Room] DHT Status: 0, Temperature: 28.9°C, Humidity: 77.9%
> [5/28/2020, 10:55:58 AM] [Room] DHT Status: 0, Temperature: 28.9°C, Humidity: 77.9%
> [5/28/2020, 10:55:58 AM] [Room] DHT Status: 0, Temperature: 28.9°C, Humidity: 77.9%
> [5/28/2020, 10:55:58 AM] [Room] DHT Status: 0, Temperature: 28.9°C, Humidity: 77.9%
> [5/28/2020, 10:55:58 AM] [Room] DHT Status: 0, Temperature: 28.9°C, Humidity: 77.9%
> [5/28/2020, 10:55:59 AM] [Room] DHT Status: 0, Temperature: 28.9°C, Humidity: 77.9%
> [5/28/2020, 10:56:00 AM] [Room] DHT Status: 0, Temperature: 28.9°C, Humidity: 77.9%
> [5/28/2020, 10:56:01 AM] [Room] DHT Status: 0, Temperature: 28.9°C, Humidity: 77.9%

But I think this is too much for refreshing the sensor and when it works like this, in my Home app, the temp and humidity shows correctly but in Config UI X Accessories tab, all accessories is missing.

**Comment by nuttdam** [comment]
It just seems to be able to capture temp and humidity but still not working correctly.

> [5/28/2020, 8:25:08 PM] [Room] DHT Status: 0, Temperature: 26.9°C, Humidity: 70.2%
[5/28/2020, 8:27:51 PM] [Room] DHT Status: 0, Temperature: 25.6°C, Humidity: 65.9%

Since Homebridge started at 11AM (server time), there are only 2 logs above. My current config is
`"refresh": "15"`

**Comment by NorthernMan54** [comment]
This is really odd as the code is pretty simple and straight forward.  Is there anything else running on the RPI that could be blocking node js from reading the temperature.

**Comment by nuttdam** [comment]
> This is really odd as the code is pretty simple and straight forward. Is there anything else running on the RPI that could be blocking node js from reading the temperature.

I have homebridge, homebridge_wol, homebridge_raspberrypi_temperature, transmission daemon and samba running on my pi.

**Comment by NorthernMan54** [comment]
I’m stuck on where to go here

The code is pretty specific around the timing of reading a temperature.  And if your setup isn’t having issue’s I don’t know where to start

**Comment by nuttdam** [comment]
I will try reinstall Raspbian and install only Homebridge. Will update to you later. Thanks,

**Comment by ghost** [comment]
I am also seeing this issue. I am able to get a reading from the DHT using other libraries.

**Comment by NorthernMan54** [comment]
Please check you config and which pin the various libraries expect to have the sensor connected to.

**Comment by nuttdam** [comment]
I have tried new clean install with only samba running and mounting one external hdd. My config is
```
"accessories": [
        {
            "accessory": "Dht",
            "name": "Room"
        }
    ],
```
The result is still 0C and 0% same as before.

Update: It came up with 1 reading and nothing updated more.
`[6/11/2020, 06:43:35] [Room] DHT Status: 0, Temperature: 25.9°C, Humidity: 65%`

**Comment by nuttdam** [comment]
The cputemp also not working.
```
"accessories": [
        {
            "accessory": "Dht",
            "name": "CPU Temperature",
            "service": "Temperature",
            "cputemp": "/usr/local/bin/cputemp"
        },
        {
            "accessory": "Dht",
            "name": "Room",
            "gpio": "4"
        }
    ]
```
This is what I get from cputemp.
```
pi@raspberrypi:~ $ /usr/local/bin/cputemp
47 C
pi@raspberrypi:~ $ cputemp
47 C
```

**Comment by NorthernMan54** [comment]
Any logs from homebridge showing any errors?

**Comment by nuttdam** [comment]
> Any logs from homebridge showing any errors?
> […](#)
> On Jun 10, 2020, at 11:41 PM, nuttdam ***@***.***> wrote: ﻿ The cputemp also not working. "accessories": [ { "accessory": "Dht", "name": "CPU Temperature", "service": "Temperature", "cputemp": "/usr/local/bin/cputemp" }, { "accessory": "Dht", "name": "Room", "gpio": "4" } ] This is what I get from cputemp. ***@***.***:~ $ /usr/local/bin/cputemp 47 C ***@***.***:~ $ cputemp 47 C — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.

No errors was shown, only this
```
[6/11/2020, 14:19:36] [Room] Initializing Dht accessory...
[6/11/2020, 14:19:36] [Room] Adding Accessory
[6/11/2020, 14:19:36] [Room] INIT: Room
```

**Comment by NorthernMan54** [comment]
Without logs or other information my ability to troubleshoot is limited and have no idea why this isn’t working.
