### ISSUE TITLE
Cannot read the sensor

### ISSUE THREAD

**Issue by YeeJiaWei** [NorthernMan54/homebridge-dht#45]
console showing 

Error: [Error: failed to read sensor]

**Comment by NorthernMan54** [comment]
Not sure how to debug this, is it wired correctly?

**Comment by aidzer0** [comment]
I’m having the same issue. Got 2 sensors, one sensor keeps going into “cannot read sensor” state, I unplug the + to the sensor and plug it back in, it reads, but a couple of hours later same issue occurs.

**Comment by aidzer0** [comment]
The logs show the below, after unplugging and plugging the positive to the bedroom sensor, it re-establishes communication.

```[8/20/2020, 08:50:31] [dht22 - Bedroom] Error: [Error: failed to read sensor]
[8/20/2020, 08:50:32] [dht22 - Lounge] DHT Status: 0, Temperature: 24.4°C, Humidity: 57.6%
[8/20/2020, 08:51:32] [dht22 - Bedroom] Error: [Error: failed to read sensor]
[8/20/2020, 08:51:33] [dht22 - Lounge] DHT Status: 0, Temperature: 24.4°C, Humidity: 57.5%
[8/20/2020, 08:52:31] [dht22 - Bedroom] Error: [Error: failed to read sensor]
[8/20/2020, 08:52:32] [dht22 - Lounge] DHT Status: 0, Temperature: 24.4°C, Humidity: 57.7%
[8/20/2020, 08:53:29] [dht22 - Bedroom] DHT Status: 0, Temperature: 23°C, Humidity: 60%

**Comment by NorthernMan54** [comment]
Not sure what I can suggest here, is it possibly a defective sensor or wiring?

**Comment by aidzer0** [comment]
I swaped out the sensors and changed out the wiring, Made sure the resistors are where they need to be, same results, the weird thing is that its not always the same sensor that becomes un-responsive. Also its only the temp side of it. Even though the error is for the unit, it shows the humidity accurately.

I am started to think this may be an incompatibility with my other plugin (tuya).  I removed tuya and had the same results after about 2 hours of up time. I am not too sure what else to check.

**Comment by NorthernMan54** [comment]
Unfortunately I don’t have a dual device setup in my environment so I can see if it works for me.

For the communications to the device I’m using this library http://www.airspayce.com/mikem/bcm2835/

Have you looked in their forums in regards this type of issue?

**Comment by aidzer0** [comment]
I have not, I will now though, thank you! I will report back if I find anything of relevance.

**Comment by JohnWickham** [comment]
Having the same problem; been working perfectly for several months, and after a reboot it continuously fails to read the sensor. I've double-checked wiring and re-installed the plugin. Here’s the relevant portion of my config.json:

```       
{
    "accessory": "Dht",
    "service": "dht22",
    "name": "Kitchen",
    "gpio": 4
}
```

**Comment by NorthernMan54** [comment]
@JohnWickham I'm just calling this library for the temperature http://www.airspayce.com/mikem/bcm2835/ do they have any comments on troubleshooting?
