### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by mikekenyon99** [NorthernMan54/homebridge-dht#46]
Hi - I have  working Homebridge Pi Zero but when I install this package I get the following error (see screenshot).  I have installed other plugin's and they worked fine.   I'm sure it's my mistake but I can't work it out. 

Thanks

Mike 

<img width="839" alt="Annotation 2020-08-18 170507" src="https://user-images.githubusercontent.com/42475982/90537238-00db0b80-e175-11ea-8dc3-d50cf355ba8b.png">

**Comment by NorthernMan54** [comment]
Try this instead

```
sudo su -
sudo npm install -g homebridge-dht
```

This is a NPM/NODE-GYP issue and not really a plugin issue

**Comment by mikekenyon99** [comment]
Hi apologies if it's not the plugin's issue - I'm still getting the same issue though.  I will look it up and if I find a solution will post back here to help other people.

**Comment by NorthernMan54** [comment]
There is this on google

https://github.com/aws-amplify/amplify-cli/issues/2023

**Comment by mikekenyon99** [comment]
Worked a treat that.  Thanks.
