### ISSUE TITLE
Turn logging off?

### ISSUE THREAD

**Issue by sharkrightnow** [NorthernMan54/homebridge-dht#56]
### Current Situation

Hi.  Is there a way to turn off logging to Homebridge logs?

### Logs

```markdown
[06/11/2024, 19:43:01] [Flat] DHT Status: 0, Temperature: 22°C, Humidity: 56%
```

### Configuration

```json
.
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

not applicable

**Comment by NorthernMan54** [comment]
Nope, no method of turning logging off
