### ISSUE TITLE
Use proxy to log data into google drive

### ISSUE THREAD

**Issue by troyliu0105** [NorthernMan54/homebridge-dht#6]
I have some problems to access google service and must use proxy, is there any ways to log data via proxy?

**Comment by NorthernMan54** [comment]
@troyliu0105 

I did a quick google, and this is feasible see below.

https://github.com/google/google-api-nodejs-client#example-specifying-a-default-proxy-and-auth-to-be-used-for-each-request

This would go into the file logger.js, in the mcuiot-logger package.
